name: Testing With Stable Client And Server

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      snjs:
        image: standardnotes/snjs
        ports:
        - 9001:9001

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Install Headless Chrome
        run: yarn global add mocha-headless-chrome
      - name: Initialize Default Configuration
        run: |
          bash ./server.sh setup
          bash ./server.sh generate-keys
      - name: Start Server
        run: bash ./server.sh start
        env:
          EXPOSED_PORT: 3123
      - name: Test
        run: bash ./server.sh test
