name: Testing With Stable Client And Server

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      snjs:
        image: standardnotes/snjs
        ports:
        - 9001:9001
      mock-event-publisher:
        image: standardnotes/mock-event-publisher
        ports:
        - 3124:3000
        env:
          LOG_LEVEL: debug
          NODE_ENV: production
          VERSION: snjs-test
          SNS_TOPIC_ARN: arn:aws:sns:us-east-1:000000000000:payments-local-topic
          SNS_ENDPOINT: http://localstack:4566
          SNS_DISABLE_SSL: true
          SNS_SECRET_ACCESS_KEY: x
          SNS_ACCESS_KEY_ID: x
          SNS_AWS_REGION: us-east-1
          NEW_RELIC_ENABLED: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Install Headless Chrome
        run: yarn global add mocha-headless-chrome
      - name: Initialize Default Configuration
        run: |
          bash ./server.sh setup
          bash ./server.sh generate-keys
      - name: Setup shorter session TTLs for testing
        run: |
          sed -i "s/5184000/4/g" docker/auth.env
          sed -i "s/31556926/7/g" docker/auth.env
          sed -i "s/259200/300/g" docker/auth.env
      - name: Start Server
        run: bash ./server.sh start
        env:
          EXPOSED_PORT: 3123
      - name: Test
        run: bash ./server.sh test
